version: '3.5'


services:
  postgres:
    container_name: postgres_demo1
    image: postgres
    environment:
      POSTGRES_USER: phuonghust2110
      POSTGRES_PASSWORD: 21102001
      PGDATA: /data/postgres
    volumes:
       - postgres-db:/data/postgres
    ports:
      - "5432:5432"


volumes:
  postgres-db:
    driver: local